name: 'Trivy Scan'
description: 'Run Trivy scan and comment on PR'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  severity:
    description: 'Severity levels to scan for'
    required: false
    default: 'HIGH,CRITICAL'
  ignore-unfixed:
    description: 'Ignore unfixed vulnerabilities'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run Trivy scan on repository
      id: trivy
      run: |
        docker run --rm -v $(pwd):/project aquasec/trivy:latest fs --severity ${{ inputs.severity }} --ignore-unfixed=${{ inputs.ignore-unfixed }} /project > trivy-output.txt || true
      shell: bash

    - name: Install jq
      run: sudo apt-get install -y jq
      shell: bash

    - name: Comment on PR with Trivy scan results
      if: always()
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        trivy_output=$(cat trivy-output.txt)
        echo "$trivy_output"
        if [ -n "${{ github.event.pull_request.number }}" ]; then
          pr_number=${{ github.event.pull_request.number }}
        else
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        fi
        if [ -n "$pr_number" ]; then
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\": \"Trivy Scan Results:\n\n\`\`\`\n$trivy_output\n\`\`\`\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/comments"
        fi
      shell: bash
