name: 'Trivy Scan'
description: 'Run Trivy scan and comment on PR'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  severity:
    description: 'Severity levels to scan for'
    required: false
    default: 'HIGH,CRITICAL'
  ignore-unfixed:
    description: 'Ignore unfixed vulnerabilities'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Run Trivy scan on local image
      id: trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasecurity/trivy:latest image --severity ${{ inputs.severity }} --ignore-unfixed=${{ inputs.ignore-unfixed }} myapp:latest > trivy-output.txt || true

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Comment on PR with Trivy scan results
      if: steps.trivy.outcome == 'failure'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        trivy_output=$(cat trivy-output.txt)
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        if [ -n "$pr_number" ]; then
          curl -s -H "Authorization: token $GITHUB_TOKEN" -X POST -d "{\"body\": \"Trivy Scan Failed:\n\n\`\`\`\n$trivy_output\n\`\`\`\"}" "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/comments"
        fi
