name: CI Pipeline with Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trivy Scan
        uses: ./.github/actions/trivy-scan
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: 'true'
