name: CI Pipeline with Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    uses: dougmendes/trivy-pr-decoration/.github/workflows/trivy-scan.yml@main
